2018-07-20 18:33:45,145 INFO: HabitTrack startup [in /home/bberastain/Desktop/habittrack/app/__init__.py:65]
2018-07-20 20:44:28,853 ERROR: Exception on /stats [GET] [in /home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/habittrack/app/main/routes.py", line 140, in stats
    today = date.today()
AttributeError: 'function' object has no attribute 'all'
2018-07-20 20:46:10,240 ERROR: Exception on /stats [GET] [in /home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/habittrack/app/main/routes.py", line 140, in stats
    today = date.today()
AttributeError: 'function' object has no attribute 'all'
2018-07-20 21:00:58,839 ERROR: Exception on /stats [GET] [in /home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/habittrack/app/main/routes.py", line 140, in stats
    today = date.today()
AttributeError: 'function' object has no attribute 'all'
2018-07-20 21:01:00,154 ERROR: Exception on /stats [GET] [in /home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bberastain/Desktop/habittrack/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bberastain/Desktop/habittrack/app/main/routes.py", line 140, in stats
    today = date.today()
AttributeError: 'function' object has no attribute 'all'
2018-07-20 21:01:13,718 INFO: HabitTrack startup [in /home/bberastain/Desktop/habittrack/app/__init__.py:65]
